version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./
        target: /app
      
  
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dbpass
    volumes:
      - type: volume 
        source: mysql
        target: /var/lib/mysql
      - type: volume
        source: mysql_config
        target: /etc/mysql

volumes:
  mysql:
  mysql_config: 
